CREATE TABLE [dbo].[CONFIGURACAO_TABELA](
	[ID_CONFIGURACAO_TABELA] [int] IDENTITY(1,1) NOT NULL,
	[BANCO_DADOS] [nvarchar](120) NOT NULL,
	[ESQUEMA] [nvarchar](120) NOT NULL,
	[TABELA] [nvarchar](120) NOT NULL,
	[JSON_COLUNAS_VISIVEIS] [nvarchar](max) NOT NULL,
	[JSON_COLUNAS_CHAVE] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CONFIGURACAO_TABELA] PRIMARY KEY CLUSTERED 
(
	[ID_CONFIGURACAO_TABELA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];


