USE [CAD_DINAMICO]
GO

/****** Object:  Table [dbo].[CONFIGURACAO_TABELA]    Script Date: 10/28/2018 6:26:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONFIGURACAO_TABELA](
	[ID_CONFIGURACAO_TABELA] [int] IDENTITY(1,1) NOT NULL,
	[BANCO_DADOS] [nvarchar](120) NOT NULL,
	[ESQUEMA] [nvarchar](120) NOT NULL,
	[TABELA] [nvarchar](120) NOT NULL,
	[JSON_COLUNAS_VISIVEIS] [nvarchar](max) NOT NULL,
	[JSON_COLUNAS_CHAVE] [nvarchar](max) NOT NULL,
	[JSON_COLUNAS_FILTRO] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CONFIGURACAO_TABELA] PRIMARY KEY CLUSTERED 
(
	[ID_CONFIGURACAO_TABELA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


