USE [CAD_DINAMICO]
GO

/****** Object:  Table [dbo].[CONFIGURACAO_TABELA]    Script Date: 10/28/2018 6:26:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONFIGURACAO_TABELA](
	[ID_CONFIGURACAO_TABELA] INT IDENTITY(1,1) NOT NULL,
	[ID_BANCO_DADOS] INT NOT NULL,
	[ID_ESQUEMA] INT NOT NULL,
	[ID_TABELA] INT NOT NULL,
	--[JSON_COLUNAS_VISIVEIS] [nvarchar](max) NOT NULL,
	--[JSON_COLUNAS_CHAVE] [nvarchar](max) NOT NULL,
	--[JSON_COLUNAS_FILTRO] [nvarchar](max) NOT NULL,
	CONSTRAINT FK_CONFIG_BD FOREIGN KEY (ID_BANCO_DADOS) REFERENCES BANCO_DADOS (ID_BANCO_DADOS),
	CONSTRAINT FK_CONFIG_ESQUEMA FOREIGN KEY (ID_ESQUEMA) REFERENCES ESQUEMA (ID_ESQUEMA),
	CONSTRAINT FK_CONFIG_TABELA FOREIGN KEY (ID_TABELA) REFERENCES TABELA (ID_TABELA),
	CONSTRAINT [PK_CONFIGURACAO_TABELA] PRIMARY KEY CLUSTERED ([ID_CONFIGURACAO_TABELA] ASC)
)
GO


