USE [CAD_DINAMICO];
GO

CREATE TABLE dbo.CONFIGURACAO_TABELA_COLUNA
(
	ID_CONFIGURACAO_TABELA_COLUNA BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_CONFIGURACAO_TABELA INT NOT NULL,
	COLUNA VARCHAR(120) NOT NULL,
	VISIVEL BIT NOT NULL DEFAULT CAST(0 AS BIT),
	COLUNA_EXIBICAO VARCHAR(120) NOT NULL,
	FILTRO BIT NOT NULL DEFAULT CAST(0 AS BIT),
	CONSTRAINT FK_CONFIG FOREIGN KEY (ID_CONFIGURACAO_TABELA) REFERENCES CONFIGURACAO_TABELA (ID_CONFIGURACAO_TABELA)
);